"""empty message

Revision ID: 670da69768ef
Revises: 28af24917ae1
Create Date: 2022-10-29 21:23:33.890451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670da69768ef'
down_revision = '28af24917ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
